version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: your_user
      DB_PASS: your_password
      DB_NAME: your_database
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: secureg
      POSTGRES_PASSWORD: appsec
      POSTGRES_DB: secureg3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
